{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pichillilorenzo.flutter_inappwebview_android",
    "module": "flutter_inappwebview_android_debug",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_debug-1.0.0.aar",
          "url": "flutter_inappwebview_android_debug-1.0.0.aar",
          "size": 542593,
          "sha512": "97df90e3c4952dbef2366d0fb6278b3b2b1f417484164afe11b7c466a49fcabffb4878ceae379198a789b9ff0059ea3f47555fcfa83782368a61b9f13a8a1da8",
          "sha256": "480a869bf50f9ab6ba319f7859b97e14ae5c92d0af71914510135ef049d1851c",
          "sha1": "80825867955d30a9ea9105256d2e362600d31f7a",
          "md5": "cefdfca8ac527d3b2b535f38d3d63a74"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_debug-1.0.0.aar",
          "url": "flutter_inappwebview_android_debug-1.0.0.aar",
          "size": 542593,
          "sha512": "97df90e3c4952dbef2366d0fb6278b3b2b1f417484164afe11b7c466a49fcabffb4878ceae379198a789b9ff0059ea3f47555fcfa83782368a61b9f13a8a1da8",
          "sha256": "480a869bf50f9ab6ba319f7859b97e14ae5c92d0af71914510135ef049d1851c",
          "sha1": "80825867955d30a9ea9105256d2e362600d31f7a",
          "md5": "cefdfca8ac527d3b2b535f38d3d63a74"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_debug-1.0.0-sources.jar",
          "url": "flutter_inappwebview_android_debug-1.0.0-sources.jar",
          "size": 231367,
          "sha512": "724dc195bfbe4b28d89808344871daa160afad873ef68cf45446c7367b99b3bef629039bef0c408ae62bce6321f437f389b09520366a50be43d8a6628dbee098",
          "sha256": "516e4f125d631258bc8b2fcddcbe2cc80259886899125edb9cb7bb536d2d0603",
          "sha1": "a1de5e80df1e9c9ddbb81872d908bc2abb82ddde",
          "md5": "8d71034285687670dcf185251ed6d329"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_debug-1.0.0-javadoc.jar",
          "url": "flutter_inappwebview_android_debug-1.0.0-javadoc.jar",
          "size": 1167849,
          "sha512": "d027d9b457fd1aaa4fff6cd48f7b6ff172b784f3a8b7992dfbe7c6c4c4ebf15b62661c0a193ec91e8c9d31419e6485ae6aaafb453d40a2dc0615f21a7490b46b",
          "sha256": "1ddbbe46974f9229bccffbd5a4ff53cddf3545b730ff4e12645693fbf2557b3c",
          "sha1": "dd69f53db9130ac4a399e715530ae93a0bea0513",
          "md5": "14962ab6221a962bd3cfc208afcd12e5"
        }
      ]
    }
  ]
}
