{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pichillilorenzo.flutter_inappwebview_android",
    "module": "flutter_inappwebview_android_profile",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.1.aar",
          "url": "flutter_inappwebview_android_profile-1.0.1.aar",
          "size": 514116,
          "sha512": "e38432d7fd3661b548ae36c11c1e968dda97189e8d074ee52a19bdbbd563499b2b14a6916cb7aff56201292c4bb9103412a2f49ee63a5ffa7d91edb6bf7e69ed",
          "sha256": "8d8105d1a320e166413387322c737552acb9c98026ed45190e4139d22d7de1e8",
          "sha1": "bc2a29359108d92f15e5ec8d6515d6b06fbd83fb",
          "md5": "c4127538131e51eeecd8875ee9e7b2eb"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.1.aar",
          "url": "flutter_inappwebview_android_profile-1.0.1.aar",
          "size": 514116,
          "sha512": "e38432d7fd3661b548ae36c11c1e968dda97189e8d074ee52a19bdbbd563499b2b14a6916cb7aff56201292c4bb9103412a2f49ee63a5ffa7d91edb6bf7e69ed",
          "sha256": "8d8105d1a320e166413387322c737552acb9c98026ed45190e4139d22d7de1e8",
          "sha1": "bc2a29359108d92f15e5ec8d6515d6b06fbd83fb",
          "md5": "c4127538131e51eeecd8875ee9e7b2eb"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.1-sources.jar",
          "url": "flutter_inappwebview_android_profile-1.0.1-sources.jar",
          "size": 231367,
          "sha512": "724dc195bfbe4b28d89808344871daa160afad873ef68cf45446c7367b99b3bef629039bef0c408ae62bce6321f437f389b09520366a50be43d8a6628dbee098",
          "sha256": "516e4f125d631258bc8b2fcddcbe2cc80259886899125edb9cb7bb536d2d0603",
          "sha1": "a1de5e80df1e9c9ddbb81872d908bc2abb82ddde",
          "md5": "8d71034285687670dcf185251ed6d329"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.1-javadoc.jar",
          "url": "flutter_inappwebview_android_profile-1.0.1-javadoc.jar",
          "size": 1167846,
          "sha512": "2b91a5bbd354bb63b05ca6786321a0f288fa81588aa2ce8215ee1a7d9121155eab0c7c16c53fd855ffbd81bb236be86fd615c65b210e05fd8d088a71c2674668",
          "sha256": "3e4aa089f44b947e430fe06130dd895a8e60ec24027c5457441f7a4ceeedaa62",
          "sha1": "bc505a9f483674a7a98cb24d2173ad07b0033bb2",
          "md5": "dc1fab8bf2c0971136174e4b78e24423"
        }
      ]
    }
  ]
}
