{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.tianma_flutter",
    "module": "flutter_release",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview_release",
          "version": {
            "requires": "1.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.9.aar",
          "url": "flutter_release-1.0.9.aar",
          "size": 4927037,
          "sha512": "36e6cb201f1b50e958404a87e0a7d5a1643fd0617e55f3c0e91ffdfc8dbe738fb57a70cfb710f49fa0445bd44eeec9e75ae83c5c1bd9e5f5773b63422612b474",
          "sha256": "f798f137f8ab343dc7ba8c66272b08adb66a7c201a8116dadd199dc2bc3ad8f7",
          "sha1": "1b4f6804690c98924a2c78a43c1ddf2348fb82a0",
          "md5": "cbcdfcac29ec8355060b32506a3932aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview_release",
          "version": {
            "requires": "1.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.9.aar",
          "url": "flutter_release-1.0.9.aar",
          "size": 4927037,
          "sha512": "36e6cb201f1b50e958404a87e0a7d5a1643fd0617e55f3c0e91ffdfc8dbe738fb57a70cfb710f49fa0445bd44eeec9e75ae83c5c1bd9e5f5773b63422612b474",
          "sha256": "f798f137f8ab343dc7ba8c66272b08adb66a7c201a8116dadd199dc2bc3ad8f7",
          "sha1": "1b4f6804690c98924a2c78a43c1ddf2348fb82a0",
          "md5": "cbcdfcac29ec8355060b32506a3932aa"
        }
      ]
    }
  ]
}
