{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pichillilorenzo.flutter_inappwebview_android",
    "module": "flutter_inappwebview_android_profile",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.0.aar",
          "url": "flutter_inappwebview_android_profile-1.0.0.aar",
          "size": 514116,
          "sha512": "e38432d7fd3661b548ae36c11c1e968dda97189e8d074ee52a19bdbbd563499b2b14a6916cb7aff56201292c4bb9103412a2f49ee63a5ffa7d91edb6bf7e69ed",
          "sha256": "8d8105d1a320e166413387322c737552acb9c98026ed45190e4139d22d7de1e8",
          "sha1": "bc2a29359108d92f15e5ec8d6515d6b06fbd83fb",
          "md5": "c4127538131e51eeecd8875ee9e7b2eb"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.0.aar",
          "url": "flutter_inappwebview_android_profile-1.0.0.aar",
          "size": 514116,
          "sha512": "e38432d7fd3661b548ae36c11c1e968dda97189e8d074ee52a19bdbbd563499b2b14a6916cb7aff56201292c4bb9103412a2f49ee63a5ffa7d91edb6bf7e69ed",
          "sha256": "8d8105d1a320e166413387322c737552acb9c98026ed45190e4139d22d7de1e8",
          "sha1": "bc2a29359108d92f15e5ec8d6515d6b06fbd83fb",
          "md5": "c4127538131e51eeecd8875ee9e7b2eb"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.0-sources.jar",
          "url": "flutter_inappwebview_android_profile-1.0.0-sources.jar",
          "size": 231367,
          "sha512": "724dc195bfbe4b28d89808344871daa160afad873ef68cf45446c7367b99b3bef629039bef0c408ae62bce6321f437f389b09520366a50be43d8a6628dbee098",
          "sha256": "516e4f125d631258bc8b2fcddcbe2cc80259886899125edb9cb7bb536d2d0603",
          "sha1": "a1de5e80df1e9c9ddbb81872d908bc2abb82ddde",
          "md5": "8d71034285687670dcf185251ed6d329"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.0-javadoc.jar",
          "url": "flutter_inappwebview_android_profile-1.0.0-javadoc.jar",
          "size": 1167849,
          "sha512": "d027d9b457fd1aaa4fff6cd48f7b6ff172b784f3a8b7992dfbe7c6c4c4ebf15b62661c0a193ec91e8c9d31419e6485ae6aaafb453d40a2dc0615f21a7490b46b",
          "sha256": "1ddbbe46974f9229bccffbd5a4ff53cddf3545b730ff4e12645693fbf2557b3c",
          "sha1": "dd69f53db9130ac4a399e715530ae93a0bea0513",
          "md5": "14962ab6221a962bd3cfc208afcd12e5"
        }
      ]
    }
  ]
}
