{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pichillilorenzo.flutter_inappwebview_android",
    "module": "flutter_inappwebview_android_profile",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.7.aar",
          "url": "flutter_inappwebview_android_profile-1.0.7.aar",
          "size": 514116,
          "sha512": "e38432d7fd3661b548ae36c11c1e968dda97189e8d074ee52a19bdbbd563499b2b14a6916cb7aff56201292c4bb9103412a2f49ee63a5ffa7d91edb6bf7e69ed",
          "sha256": "8d8105d1a320e166413387322c737552acb9c98026ed45190e4139d22d7de1e8",
          "sha1": "bc2a29359108d92f15e5ec8d6515d6b06fbd83fb",
          "md5": "c4127538131e51eeecd8875ee9e7b2eb"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.7.aar",
          "url": "flutter_inappwebview_android_profile-1.0.7.aar",
          "size": 514116,
          "sha512": "e38432d7fd3661b548ae36c11c1e968dda97189e8d074ee52a19bdbbd563499b2b14a6916cb7aff56201292c4bb9103412a2f49ee63a5ffa7d91edb6bf7e69ed",
          "sha256": "8d8105d1a320e166413387322c737552acb9c98026ed45190e4139d22d7de1e8",
          "sha1": "bc2a29359108d92f15e5ec8d6515d6b06fbd83fb",
          "md5": "c4127538131e51eeecd8875ee9e7b2eb"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.7-sources.jar",
          "url": "flutter_inappwebview_android_profile-1.0.7-sources.jar",
          "size": 231367,
          "sha512": "724dc195bfbe4b28d89808344871daa160afad873ef68cf45446c7367b99b3bef629039bef0c408ae62bce6321f437f389b09520366a50be43d8a6628dbee098",
          "sha256": "516e4f125d631258bc8b2fcddcbe2cc80259886899125edb9cb7bb536d2d0603",
          "sha1": "a1de5e80df1e9c9ddbb81872d908bc2abb82ddde",
          "md5": "8d71034285687670dcf185251ed6d329"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_profile-1.0.7-javadoc.jar",
          "url": "flutter_inappwebview_android_profile-1.0.7-javadoc.jar",
          "size": 1167935,
          "sha512": "3a8c71de2cb843ebbb8d757632800f46cf12dcb9eb6fa34e3e79c2de7c14e34cb319b7e2ff68f5a8c223bd578f6686a5cce137f3b094e9bf4383150d4781dc13",
          "sha256": "26337598f1736340947deab83c001b56d9b8c2d2bd2da4e5baef6093fb90afde",
          "sha1": "ccf79ece2601641b2215763620ad9ff8dfefe163",
          "md5": "5740de8ff08767d5d68cbbd53484f70e"
        }
      ]
    }
  ]
}
