{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.my_flutter_module",
    "module": "flutter_debug",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview_android",
          "module": "flutter_inappwebview_android_debug",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.0.aar",
          "url": "flutter_debug-1.0.0.aar",
          "size": 17607036,
          "sha512": "687baef4e1e658d78bab952335c92e3a9ca2a6a86fecb9968e623bcbb55bdb9ca83cb0bf18b794d99340b6cbf7e13f55ec61e1daa85a6e9c9cc83288cc746062",
          "sha256": "6bfdad889923362a26bfd257887b1ef644a20cb8a6b42a88b88c551ff30bd2ae",
          "sha1": "3f419bc5c110d420095a3698f4ac0f0d2726f5b8",
          "md5": "7acf02a0b9e961272861957e41c4a7a4"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview_android",
          "module": "flutter_inappwebview_android_debug",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.0.aar",
          "url": "flutter_debug-1.0.0.aar",
          "size": 17607036,
          "sha512": "687baef4e1e658d78bab952335c92e3a9ca2a6a86fecb9968e623bcbb55bdb9ca83cb0bf18b794d99340b6cbf7e13f55ec61e1daa85a6e9c9cc83288cc746062",
          "sha256": "6bfdad889923362a26bfd257887b1ef644a20cb8a6b42a88b88c551ff30bd2ae",
          "sha1": "3f419bc5c110d420095a3698f4ac0f0d2726f5b8",
          "md5": "7acf02a0b9e961272861957e41c4a7a4"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0.0-sources.jar",
          "url": "flutter_debug-1.0.0-sources.jar",
          "size": 1129,
          "sha512": "f09819ae3f5efad5acdb33762e49253834936296ece4f7e3796fc68b38b12ce0d6d393ff242f6eb0aabd582394bbde1db4ddd60915b83cf078562e17d46fc07b",
          "sha256": "2b9ce0e9d5f139ebd8311c81490be3ceb740a73ab36dc7bd5aa6ced6c453f071",
          "sha1": "1512a06bae874fb2c01b520526050fa582fc5fc9",
          "md5": "b86738f38964c09d55452a6c1e62f243"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0.0-javadoc.jar",
          "url": "flutter_debug-1.0.0-javadoc.jar",
          "size": 261619,
          "sha512": "e542c6b74ecb90fca52180554ed54d72c43c95b50710a5f8fc72ec70b98e08bee88465be27139ee27a80ab427bbd3937f6b2ef5e9682dd93808d5cdf94434008",
          "sha256": "7e5a81afe78872d67e9d851d6ac5c65c83505ac2a6998bd5f0251c3d9442b23c",
          "sha1": "de0fa6f235f008125853761ae60bdd2499d2dea3",
          "md5": "9fee58e0c7cd6574cb89a5e2ef6bf1c5"
        }
      ]
    }
  ]
}
