{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pichillilorenzo.flutter_inappwebview_android",
    "module": "flutter_inappwebview_android_release",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1.0.0.aar",
          "url": "flutter_inappwebview_android_release-1.0.0.aar",
          "size": 427687,
          "sha512": "fc517c9416a8643f59b1a275260d33a50fd1364c93cfa606ba7ea5c4cbb3b49dd5bbf10d86ab918f1e06e4859400b339e4ca4f2b4f7401f29a56a1944f3ecc36",
          "sha256": "c66bbf2e0e8ab096f3a6a824e8b267069ba060c0932978217cb5fbc9a13f0ea0",
          "sha1": "39c87bd4552545c787d21cbec2a9e9b33646798d",
          "md5": "72a5783441583c1c136174532708aa82"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1.0.0.aar",
          "url": "flutter_inappwebview_android_release-1.0.0.aar",
          "size": 427687,
          "sha512": "fc517c9416a8643f59b1a275260d33a50fd1364c93cfa606ba7ea5c4cbb3b49dd5bbf10d86ab918f1e06e4859400b339e4ca4f2b4f7401f29a56a1944f3ecc36",
          "sha256": "c66bbf2e0e8ab096f3a6a824e8b267069ba060c0932978217cb5fbc9a13f0ea0",
          "sha1": "39c87bd4552545c787d21cbec2a9e9b33646798d",
          "md5": "72a5783441583c1c136174532708aa82"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1.0.0-sources.jar",
          "url": "flutter_inappwebview_android_release-1.0.0-sources.jar",
          "size": 231367,
          "sha512": "724dc195bfbe4b28d89808344871daa160afad873ef68cf45446c7367b99b3bef629039bef0c408ae62bce6321f437f389b09520366a50be43d8a6628dbee098",
          "sha256": "516e4f125d631258bc8b2fcddcbe2cc80259886899125edb9cb7bb536d2d0603",
          "sha1": "a1de5e80df1e9c9ddbb81872d908bc2abb82ddde",
          "md5": "8d71034285687670dcf185251ed6d329"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1.0.0-javadoc.jar",
          "url": "flutter_inappwebview_android_release-1.0.0-javadoc.jar",
          "size": 1167916,
          "sha512": "02272460aaaf013519864f1a5a5e45a767149b1fb3bc225e837ca1938c06ffdab2c0256c517978e45abadbbf289047cb6223ee17e5e8cca4a7c7cb4c6a1fec10",
          "sha256": "1096515c27419d5a30ca84248209c39296083b652e51e201fa30750b65f7887b",
          "sha1": "d5cb8fa92dac6b8e67040519c9c815005da3472c",
          "md5": "0ae73ac4e1c192d7ad0fa73db653eac3"
        }
      ]
    }
  ]
}
