{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pichillilorenzo.flutter_inappwebview_android",
    "module": "flutter_inappwebview_android_release",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1.0.7.aar",
          "url": "flutter_inappwebview_android_release-1.0.7.aar",
          "size": 427687,
          "sha512": "fc517c9416a8643f59b1a275260d33a50fd1364c93cfa606ba7ea5c4cbb3b49dd5bbf10d86ab918f1e06e4859400b339e4ca4f2b4f7401f29a56a1944f3ecc36",
          "sha256": "c66bbf2e0e8ab096f3a6a824e8b267069ba060c0932978217cb5fbc9a13f0ea0",
          "sha1": "39c87bd4552545c787d21cbec2a9e9b33646798d",
          "md5": "72a5783441583c1c136174532708aa82"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1.0.7.aar",
          "url": "flutter_inappwebview_android_release-1.0.7.aar",
          "size": 427687,
          "sha512": "fc517c9416a8643f59b1a275260d33a50fd1364c93cfa606ba7ea5c4cbb3b49dd5bbf10d86ab918f1e06e4859400b339e4ca4f2b4f7401f29a56a1944f3ecc36",
          "sha256": "c66bbf2e0e8ab096f3a6a824e8b267069ba060c0932978217cb5fbc9a13f0ea0",
          "sha1": "39c87bd4552545c787d21cbec2a9e9b33646798d",
          "md5": "72a5783441583c1c136174532708aa82"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1.0.7-sources.jar",
          "url": "flutter_inappwebview_android_release-1.0.7-sources.jar",
          "size": 231367,
          "sha512": "724dc195bfbe4b28d89808344871daa160afad873ef68cf45446c7367b99b3bef629039bef0c408ae62bce6321f437f389b09520366a50be43d8a6628dbee098",
          "sha256": "516e4f125d631258bc8b2fcddcbe2cc80259886899125edb9cb7bb536d2d0603",
          "sha1": "a1de5e80df1e9c9ddbb81872d908bc2abb82ddde",
          "md5": "8d71034285687670dcf185251ed6d329"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_release-1.0.7-javadoc.jar",
          "url": "flutter_inappwebview_android_release-1.0.7-javadoc.jar",
          "size": 1167935,
          "sha512": "3a8c71de2cb843ebbb8d757632800f46cf12dcb9eb6fa34e3e79c2de7c14e34cb319b7e2ff68f5a8c223bd578f6686a5cce137f3b094e9bf4383150d4781dc13",
          "sha256": "26337598f1736340947deab83c001b56d9b8c2d2bd2da4e5baef6093fb90afde",
          "sha1": "ccf79ece2601641b2215763620ad9ff8dfefe163",
          "md5": "5740de8ff08767d5d68cbbd53484f70e"
        }
      ]
    }
  ]
}
