{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pichillilorenzo.flutter_inappwebview_android",
    "module": "flutter_inappwebview_android_debug",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_debug-1.0.8.aar",
          "url": "flutter_inappwebview_android_debug-1.0.8.aar",
          "size": 542593,
          "sha512": "97df90e3c4952dbef2366d0fb6278b3b2b1f417484164afe11b7c466a49fcabffb4878ceae379198a789b9ff0059ea3f47555fcfa83782368a61b9f13a8a1da8",
          "sha256": "480a869bf50f9ab6ba319f7859b97e14ae5c92d0af71914510135ef049d1851c",
          "sha1": "80825867955d30a9ea9105256d2e362600d31f7a",
          "md5": "cefdfca8ac527d3b2b535f38d3d63a74"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_inappwebview_android_debug-1.0.8.aar",
          "url": "flutter_inappwebview_android_debug-1.0.8.aar",
          "size": 542593,
          "sha512": "97df90e3c4952dbef2366d0fb6278b3b2b1f417484164afe11b7c466a49fcabffb4878ceae379198a789b9ff0059ea3f47555fcfa83782368a61b9f13a8a1da8",
          "sha256": "480a869bf50f9ab6ba319f7859b97e14ae5c92d0af71914510135ef049d1851c",
          "sha1": "80825867955d30a9ea9105256d2e362600d31f7a",
          "md5": "cefdfca8ac527d3b2b535f38d3d63a74"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_debug-1.0.8-sources.jar",
          "url": "flutter_inappwebview_android_debug-1.0.8-sources.jar",
          "size": 231367,
          "sha512": "724dc195bfbe4b28d89808344871daa160afad873ef68cf45446c7367b99b3bef629039bef0c408ae62bce6321f437f389b09520366a50be43d8a6628dbee098",
          "sha256": "516e4f125d631258bc8b2fcddcbe2cc80259886899125edb9cb7bb536d2d0603",
          "sha1": "a1de5e80df1e9c9ddbb81872d908bc2abb82ddde",
          "md5": "8d71034285687670dcf185251ed6d329"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_inappwebview_android_debug-1.0.8-javadoc.jar",
          "url": "flutter_inappwebview_android_debug-1.0.8-javadoc.jar",
          "size": 1167826,
          "sha512": "708910a42b395a9a780fb525f0a3d59fb66d55f178ee01641f483fca8e59fa5bfc0f2736338d0b521629c9415f014bfe831f33cd13244f758857812ce5e26e64",
          "sha256": "ed2afcbd648986e1d1b6f5bf157916b13721cc4871036edec7a32300e7689799",
          "sha1": "6ecc7d1613231f30b3d07d42a3d734c94f748316",
          "md5": "97c62beb41bea9fd30eccb9c692b0a62"
        }
      ]
    }
  ]
}
