{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.tianma_flutter",
    "module": "flutter_profile",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview_profile",
          "version": {
            "requires": "1.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.9.aar",
          "url": "flutter_profile-1.0.9.aar",
          "size": 7498920,
          "sha512": "332ca8f17ca171ab908e797ce3356d587eac1ab2b51998f3f734dbb562c476d3579cb9b38b949c90d71e5db2235f150db91567a9e161f9c5cd8bfa1290b97251",
          "sha256": "8a93cbe5d4912ed085fdb111568d23c06dede9686af2644acbfd36e704099bf9",
          "sha1": "7ce864e844ad09450699accf66231deb06cdf756",
          "md5": "0a697c9cc95e594fc1947f0e4fc36bf4"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview",
          "module": "flutter_inappwebview_profile",
          "version": {
            "requires": "1.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.9.aar",
          "url": "flutter_profile-1.0.9.aar",
          "size": 7498920,
          "sha512": "332ca8f17ca171ab908e797ce3356d587eac1ab2b51998f3f734dbb562c476d3579cb9b38b949c90d71e5db2235f150db91567a9e161f9c5cd8bfa1290b97251",
          "sha256": "8a93cbe5d4912ed085fdb111568d23c06dede9686af2644acbfd36e704099bf9",
          "sha1": "7ce864e844ad09450699accf66231deb06cdf756",
          "md5": "0a697c9cc95e594fc1947f0e4fc36bf4"
        }
      ]
    }
  ]
}
