{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.my_flutter_module",
    "module": "flutter_release",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview_android",
          "module": "flutter_inappwebview_android_release",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.7.aar",
          "url": "flutter_release-1.0.7.aar",
          "size": 5005151,
          "sha512": "7bb187365c576ff47061a38a30e8f5f0cd44fb240adcafc0418dc965c68aa35b0290be3e306cac7a66b10fc85d16f513061a3fb245eceb7e97f21489771cc94e",
          "sha256": "607f4f1ea1a785a06adc5c1600a354095b1ccaccb1eb026a3fd0f1206d53edb1",
          "sha1": "8b5ed753210351328f6c320c86b7ee05d87695f6",
          "md5": "cf2cdfb22d09f1afb84069b01c6adc81"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-82bd5b7209295a5b7ff8cae0df96e7870171e3a5"
          }
        },
        {
          "group": "com.pichillilorenzo.flutter_inappwebview_android",
          "module": "flutter_inappwebview_android_release",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.7.aar",
          "url": "flutter_release-1.0.7.aar",
          "size": 5005151,
          "sha512": "7bb187365c576ff47061a38a30e8f5f0cd44fb240adcafc0418dc965c68aa35b0290be3e306cac7a66b10fc85d16f513061a3fb245eceb7e97f21489771cc94e",
          "sha256": "607f4f1ea1a785a06adc5c1600a354095b1ccaccb1eb026a3fd0f1206d53edb1",
          "sha1": "8b5ed753210351328f6c320c86b7ee05d87695f6",
          "md5": "cf2cdfb22d09f1afb84069b01c6adc81"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0.7-sources.jar",
          "url": "flutter_release-1.0.7-sources.jar",
          "size": 1129,
          "sha512": "f09819ae3f5efad5acdb33762e49253834936296ece4f7e3796fc68b38b12ce0d6d393ff242f6eb0aabd582394bbde1db4ddd60915b83cf078562e17d46fc07b",
          "sha256": "2b9ce0e9d5f139ebd8311c81490be3ceb740a73ab36dc7bd5aa6ced6c453f071",
          "sha1": "1512a06bae874fb2c01b520526050fa582fc5fc9",
          "md5": "b86738f38964c09d55452a6c1e62f243"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-1.0.7-javadoc.jar",
          "url": "flutter_release-1.0.7-javadoc.jar",
          "size": 261621,
          "sha512": "d645c8ade8cff2fe365386a0cf323bbf0938150bb602383242b25e33e051ebfa22de5038d591d464204e7f48a49f9b5e3da8b6a7e5684801f4ac15289fc5b068",
          "sha256": "16518c2f23ab25ac23fec19fcb974f9684e4d4b38141e75e61df5a3b3593cac2",
          "sha1": "321cd4dcca69ed70ca60dd594e7a7fa0810a75da",
          "md5": "0aeab8977ecce7d5cf6d8e2aba5dab37"
        }
      ]
    }
  ]
}
